accordion task solution
js-tasks-ru/htmlcss-20231222_murzinoff-ivan pull request #7
Opened 2024-01-10 13:30 UTC by IMurzinov

2024-01-10 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-10 21:12 UTC, GSemikozov requested changes

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200&display=swap');
шрифты подключаем в assets/css/fonts.css

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
это элемент блока, а не блок (верстаем 1 аккордион с 3 секциями, а не 3 отдельных аккордиона)

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 35%;
лишнее

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +
не хватает паддингов

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline;
а почему инлайн? не подходит

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 10px;
если паддинги зададим на уровне родителя, то тут уже не надо заморачиваться

2024-01-10 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
не хватает отступа сверху + при открытом состоянии паддинг у элемента блока будет другой

2024-01-12 08:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-12 08:58 UTC, IMurzinov commented
Переподключил шрифт, переписал код так, чтобы был один аккордеон и внутри него 3 айтема. Добавил паддинги так, чтобы было похоже на стайлгайд. По поводу display: inline : summary у нас по умолчанию inline, но у меня почему-то, если я это явно не пропишу, не исчезает стрелка состояния открыто/закрыто, не понимаю, как решить эту проблему. А width я прописал, чтобы аккордеон, который у нас по умолчанию display: block, не занимал всю строку, тоже не додумался, как по-другому это сделать

2024-01-14 17:01 UTC, GSemikozov requested changes

2024-01-14 17:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 35%;
не исправлено

2024-01-14 17:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 20px;
справа тоже нужен

2024-01-14 17:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline;
не исправлено (надо убрать)

2024-01-14 17:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
не исправлено

2024-01-14 21:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-18 22:05 UTC, closed without merging