flexbox-containers and cards added
js-tasks-ru/htmlcss-20231222_murzinoff-ivan pull request #8
Opened 2024-01-16 21:41 UTC by IMurzinov

2024-01-16 21:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-16 21:45 UTC, IMurzinov commented
Возникло несколько вопросов: 
1) Все ли контейнеры мы делаем флексами?
2) Есть ли способ прижать края элемента к cross axis? Футер у меня row-direction: column --> два элемента друг над другом, но растягиваются на всю по горизонтали. Или это чисто отступами делается?
3) Надо ли footer'у задавать фиксированную высоту?
4) У меня page какую-то странную часть экрана занимает. По идее, он должен покрывать всю страницу, включая footer.
А он у меня обрывается где-то по середине, почему так?

2024-01-17 12:02 UTC, GSemikozov requested changes

2024-01-17 12:02 UTC, GSemikozov commented on components/footer/footer.css
> +    padding: 0 235px;
лучше ограничивать ширину через max-width

2024-01-17 12:05 UTC, GSemikozov commented
> Возникло несколько вопросов:
> 
> 1. Все ли контейнеры мы делаем флексами?
> 2. Есть ли способ прижать края элемента к cross axis? Футер у меня row-direction: column --> два элемента друг над другом, но растягиваются на всю по горизонтали. Или это чисто отступами делается?
> 3. Надо ли footer'у задавать фиксированную высоту?
> 4. У меня page какую-то странную часть экрана занимает. По идее, он должен покрывать всю страницу, включая footer.
>    А он у меня обрывается где-то по середине, почему так?

1. контейнер как компонент делать флексом не надо, иначе придется предоставлять возможность через модификаторы менять direction и выравнивание. В нашем случае, если речь именно про container, то контейнер выполняет лишь роль центрирования контента. Если же речь про любые блоки которые могут быть контейнерами для других блоков - тут надо смотреть на контекст, не нужно все блоки делать флексами по умолчанию, зачастую это излишество.
2. это делается через max-width
3. нет
4.

2024-01-18 22:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-18 22:26 UTC, IMurzinov commented
скриншот по поводу проблемы с размерами page
![Снимок экрана (17)](https://github.com/js-tasks-ru/htmlcss-20231222_murzinoff-ivan/assets/151651086/35686776-a89c-4b85-9a70-1087253b9f55)

2024-01-19 07:24 UTC, GSemikozov commented
> скриншот по поводу проблемы с размерами page ![Снимок экрана (17)](https://private-user-images.githubusercontent.com/151651086/297896558-35686776-a89c-4b85-9a70-1087253b9f55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDkwODcsIm5iZiI6MTcwNTY0ODc4NywicGF0aCI6Ii8xNTE2NTEwODYvMjk3ODk2NTU4LTM1Njg2Nzc2LWE4OWMtNGI4NS05YTcwLTEwODcyNTNiOWY1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNzE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWI5YTNlOGFkMzAxZGMzMGJlZWZiMWM5MjQxMzljOWU2MjM3ZjZiMjhjOWM2NjQwZTI5N2E3NzE0NmFhYmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eypVVsO3SkkeUkgmgWZL5mTTpv3hL1Uq1I6kyGOgzb0)

может дело в масштабе. Как вариант, можно заменить height: 100% на min-height: 100vh у body

2024-01-19 12:42 UTC, IMurzinov commented
min-height: 100vh сработало. Теперь page занимает всю страницу, как надо, спасибо

2024-01-21 14:43 UTC, GSemikozov approved these changes

2024-01-21 14:43 UTC, merged